### ISSUE TITLE
./osvc-rest-darwin-amd64 report panic 

### ISSUE THREAD

**Issue by 065673** [rajangdavis/osvc-rest#2]
report function doesn't appear to work on Mac OS X Mojave 

/osvc-rest-darwin-amd64 report
panic: unable to redefine 'o' shorthand in "report" flagset: it's already used for "offset" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc420108400, 0xc420097040)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/pflag/flag.go:862 +0x72b
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc420097040)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/pflag/flag.go:875 +0x71
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc420108900, 0xc420057c18)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/pflag/flag.go:278 +0xa0
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc420108400, 0xc420108900)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/pflag/flag.go:873 +0x50
github.com/spf13/cobra.(*Command).mergePersistentFlags(0x155c8e0)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/cobra/command.go:1495 +0x90
github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0x155c8e0)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/cobra/command.go:906 +0x2f
github.com/spf13/cobra.(*Command).execute(0x155c8e0, 0x157f120, 0x0, 0x0, 0x155c8e0, 0x157f120)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/cobra/command.go:686 +0x59
github.com/spf13/cobra.(*Command).ExecuteC(0x155cb40, 0x12c2e4c, 0x0, 0x155cda0)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x155cb40, 0xc42001c0b8, 0x0)
	C:/Users/rajan/Desktop/go_projects/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/rajangdavis/osvc-rest/cmd.Execute()
	C:/Users/rajan/Desktop/go_projects/src/github.com/rajangdavis/osvc-rest/cmd/root.go:22 +0x2d
main.main()
	C:/Users/rajan/Desktop/go_projects/src/github.com/rajangdavis/osvc-rest/main.go:6 +0x20

**Comment by rajangdavis** [comment]
[I just updated the package](https://github.com/rajangdavis/osvc-rest/releases/tag/v1.1-beta).

I tested it out on my laptop (Windows) and it should work as golang works in a cross platform capacity. 

Can you let me know if this works for you? I will close out the issue when you have confirmed.

**Comment by 065673** [comment]
It works fine on Windows. Thanks!
